---

- hosts: localhost
  become: yes
  connection: local

  roles:
    - role: custom-openblas
      vars:
        OPENBLAS_VERSION: '{{ version | default("v0.3.3") }}'
        BUILD_DIR: '{{ build_dir | default("/tmp/openblas_build") }}'
        INSTALL_DIR: '{{ install_dir | default("/opt/OpenBLAS") }}'
        PREREQS: '{{ install_required | default("no") }}'
        COMMON: '{{ CFLAGS | default("-O3 -m64 -mtune=generic -march=x86-64 -fPIC") }}'
        USE_THREAD: '{{ use_threading | default("1") }}'
        USE_OPENMP: '{{ use_openmp | default("0") }}'
        CC: '{{ c_compiler | default("gcc") }}'
        FC: '{{ fortran_compiler | default("gfortran") }}'
      tags: 'custom-openblas'

    - role: openblas-default-multithreaded
      tags: 'openblasp'

    - role: openblas-openmpi
      tags: 'openblaso'

    - role: openblas-standard
      tags: 'openblas'
