- name: Install required packages for building OpenBLAS (only if this option is specified)
  yum:
    name: ['make', 'gcc', 'gcc-gfortran', 'libgfortran', 'git']
  when: "'yes' == PREREQS"

- name: Create locales file and populate it
  copy:
    dest: "/etc/sysconfig/i18n"
    content: |
      LANG="en_US.UTF-8"
      LC_ALL="C"
      LANGUAGE="C"

- debug:
    msg: "{{ lookup('file', '/etc/sysconfig/i18n') }}"