---
- name: Yum epel
  yum:
    name: ['https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm']

- name: chmod /et/passed
  file: 
    path: /etc/passwd
    owner: root 
    group: root 
    mode: 01777

- name: User specific rpms
  yum:
    name: ['unzip', 'wget', 'openblas-threads64', 'openblas-devel']

- name: Install required packages for building OpenBLAS (only if this option is specified)
  yum:
    name: ['make', 'gcc', 'gcc-gfortran', 'libgfortran', 'git']
  when: "'yes' == PREREQS"

- name: Create locales file and populate it
  copy:
    dest: "/etc/sysconfig/i18n"
    content: |
      LANG="en_US.UTF-8"
      LC_ALL="C"
      LANGUAGE="C"

- debug:
    msg: "{{ lookup('file', '/etc/sysconfig/i18n') }}"