---

- hosts: localhost
  become: yes
  connection: local

  roles:
    - role: build_environment
      vars:
        OPENBLAS_VERSION: "{{ lookup('env','OPENBLAS_VERSION') }}"
        BUILD_DIR: '{{ build_dir | default("/tmp/openblas_build") }}'
        INSTALL_DIR: '{{ install_dir | default("/opt/OpenBLAS") }}'
        PREREQS: '{{ install_required | default("no") }}'
        COMMON: "{{ lookup('env','CFLAGS') }}"
        USE_THREAD: "{{ lookup('env', 'USE_THREADING') | default('1') }}"
        USE_OPENMP: "{{ lookup('env', 'USE_OPENMP') | default('0') }}"
        CC: '{{ c_compiler | default("gcc") }}'
        FC: '{{ fortran_compiler | default("gfortran") }}'
      tags: 'build_environment'

    - role: compile_test
      tags: 'compile_test'

